### ISSUE TITLE
Managing a technical product: the role of the PM in a development team

### ISSUE THREAD

**Issue by pvcarrera** [soulim/codeandbeyond#12]
### Intro

Hello and welcome to a new episode of Code && Beyond. A podcast where we talk about software development and anything beyond that.

Today I'm here  with my friend Alex and a special guest: Robyn Farah. Welcome Robyn!

Robyn has been working as a pm (project manager) for more than X years so we have invited her today to talk a bit about her role and how pms can help to guide a technical product in the right direction.

But first of all Robyn, could you introduce yourself?

### Highlights of the week

-   Alex: TODO
-   Pablo: TODO

### Q/A

- How would you describe the work of a project manager?
- How do you balance stakeholders requirements and what your team can achieve?
- How do you prioritize? Any tools/processes?
- How to find the balance in the team: devs, qas. Specialist vs generalist
- What are the abilities or skill you appreciate in developers?
- And the ones you don't like?
- What are your thoughts about tools and frameworks: example: Agile frameworks: Scrum, Kanban, etc. ?
- Summary

### Outro
- (Good bye Robyn)

Okay! That's it for today. Thank you for listening! 🙂

In case of any questions, simply send us an email at "codeandbeyond at protonmail.com". You will also find the address in the show notes.

If you are listening to our show on Spotify. Don't forget to leave us a rating!

Keep being amazing! Bye! 👋🙂

### Title

```
Managing a technical product: the role of a product manager in a development team
```

### Show notes

```
This time Pablo and Alex are joined by a special guest: Robyn Farah.

Robyn has been working as a product manager for more than 5 years. So we have invited her to talk a bit about her role and how product managers can help to guide a technical team in the right direction. We are going to touch on topics of:

- using data to prioritize tasks and features,
- finding a common language between software engineers and managers,
- abbreviations and The Cooking Chicken Method.

---

Have any feedback? Send us an email at <codeandbeyond@protonmail.com>.

Check other episodes of the podcast at <https://codeandbeyond.rocks/> and don't forget to give a rating on Spotify ;)

*Music by [penguinmusic](https://pixabay.com/users/penguinmusic-24940186) from [Pixabay](https://pixabay.com/music).*
```

**Comment by soulim** [comment]
Published at https://codeandbeyond.rocks/episodes/c9d35403-d894-4c3c-8d67-7fb115f24a0e-managing-a-technical-product/.
