### ISSUE TITLE
Code & Chess

### ISSUE THREAD

**Issue by pvcarrera** [soulim/codeandbeyond#7]
### Intro
Hello and welcome to a new episode of Code && Beyond. A podcast where we talk about software development and anything beyond that.

I'm Pablo and today I'm here with my friend Alex and a new special guest José Doval (Pepe).

Pepe and I have been friends for a long time. We studied CS at the same university and even built a company together (not a very successful one). Back in the day, I used to think that he was a talented software developer who loved chess. These days, I'm not so sure anymore. I'm starting to think that he is a chess player who likes software development :-)

So Pepe, please introduce yourself and let's try to solve this mistery :-)

### Q/A
- Tell us a bit about yourself and your background.
- Do you consider yourself a chess player who codes or the other way around?
- Do you see any similarities between playing chess and coding? Anything that can be applied to both worlds?
- Does the chess player mind help you in your software developer work?
- Do you know how is the state of chess AI? is it used for training? competitions? etc.

### Outro

Okay! That's it for today. Thank you for listening! 🙂

Mention Pepe's Twitch channel?

In case of any questions, simply send us an email at "codeandbeyond at protonmail.com". You will also find the address in the show notes.

If you are listening to our show on Spotify. Don't forget to leave us a rating!

Keep being amazing! Bye! 👋🙂

### Title

```
Code & Chess
```

### Description

```
This time Alex and Pablo welcome a new special guest, José Doval (Pepe). Pepe is a chess player/teacher who writes code for a living.

In this episode of Code && Beyond we talk about machines playing chess, how chess skills could be applied in software engineering and beyond it.
```

### Show notes

```
- Pepe Doval on Twitter, https://twitter.com/pepellou
- Pepe Doval on Twitch, https://www.twitch.tv/pepellou
- Pepe Doval on GitHub, https://github.com/pepellou
- Chessable,
  https://www.chessable.com/
- "How Life Imitates Chess" (book),
  https://en.wikipedia.org/wiki/How_Life_Imitates_Chess
- AlphaZero is a computer program developed by artificial intelligence research company DeepMind to master the games of chess, shogi and go.
  See https://en.wikipedia.org/wiki/AlphaZero
- MuZero is a computer program developed by artificial intelligence research company DeepMind to master games without knowing their rules.
  See https://en.wikipedia.org/wiki/MuZero.
- Correspondence chess is chess played by various forms of long-distance correspondence, traditionally through the postal system.
  See https://en.wikipedia.org/wiki/Correspondence_chess
```

**Comment by soulim** [comment]
Episode: https://anchor.fm/codeandbeyond/episodes/Code--Chess-e1du6f2.
